config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "blogs#index"
  resources :blogs do
    resources :comments, only: :create
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title,presence: true
  validates :image,presence: true
  validates :matter,presence: true

  belongs_to :user
  has_one_attached :image
  has_many :comments
  has_many :tags,through: :blog_tag_relations
  has_many :blog_tag_relations
end

app/models/blog_tag_relation.rb
class BlogTag

    include ActiveModel::Model
    attr_accessor :message, :name
  
    with_options presence: true do
      validates :message
      validates :key_name
    end
  
    def save
      blog = Blog.create(message: message)
      tag = Tag.create(key_name: key_name)
  
      BlogTagRelation.create(blog_id: blog.id, tag_id: tag.id)
    end
  end
  belongs_to :blog
  belongs_to :tag
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  belongs_to :user

  validates :text,presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :blog_tag_relations
  has_many :blogs,through: :blog_tag_relations

  validates :key_name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blogs
  has_many :comments

             validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
before_action :move_to_index, except: [:index, :show]

  def index
    @blogs = Blog.includes(:user).order("created_at DESC")
  end

  def new
    @blog = Blog.new
  end
  
  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @blog = Blog.find(params[:id])
    @comment = Comment.new
    @comments = @blog.comments.includes(:user)
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    blog = Blog.find(params[:id])
    if blog.update(blog_params)
      redirect_to  blog_path(blog.id)
    else
      render :edit
    end
  end

  def destroy
    blog = Blog.find(params[:id])
    blog.destroy
    redirect_to root_path
  end
  
  private
  def blog_params
    params.require(:blog).permit(:title,:matter,:image).merge(user_id: current_user.id)
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to blog_path(@comment.blog)
    else
      @blog = @comment.blog
      @comments = @blog.comments
      render "blogs/show"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, blog_id: params[:blog_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @name = user.name
    @blogs = user.blogs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with model: @blog,id: 'new_message',local: true do |f|%>
  <div class="field">
    <%= f.label :title, "タイトル" %><br />
    <%= f.text_field :title ,size: 50 %>
  </div>

  <div class="field">
    <%= f.label :matter, "記事内容" %><br />
    <%= f.text_area :matter, class: :form__text,rows:10 %>
  </div>

  <div class="field">
    <%= f.label :image, "画像" %><br />
    <%= f.file_field :image %>
  </div>

  <div id="image-list"></div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>
<%= image_tag @blog.image, id: 'image' if @blog.image.present? %> 

app/views/blogs/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <%= render partial: "form",locals: {blog: @blog }%>
    </div>
  </div>
</div>

app/views/blogs/index.html.erb
<main class="main">
  <div class="inner"> 
    <div class="card__wrapper">
       <% @blogs.each do |blog| %>
       <div class="card">
         <%= link_to blog_path(blog.id) do %>
         <%= image_tag blog.image, class: "card__img" %>
      <div class="card__body">
         <%= link_to blog.title, blog_path(blog.id), class: :card__title%>
         <%= l blog.created_at %>
         <%= link_to blog.user.name, user_path(blog.user.id), class: :card__user %>
        </div>
       </div>
       <% end %>
      <% end %>
      </div>
    </div>
  </div>
  <%= link_to(new_blog_path, class: 'purchase-btn') do %>
     <span class='purchase-btn-text'>投稿</span>
     <%= image_tag 'memo.png' , size: '185x50' ,class: "purchase-btn-icon" %>
   <% end %>
</main>

app/views/blogs/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
        <%= render partial: "form",locals: {blog: @blog }%>
    </div>
  </div>
</div>

app/views/blogs/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
    <div class="show_time">
   <%= l @blog.created_at %>
    <% if user_signed_in? && current_user.id == @blog.user_id %>
   <% unless @blog.user.email == "test@example.com"%>
    <div class="prototype__manage">
          <%= link_to "編集する", edit_blog_path(@blog.id), method: :get, class: :prototype__btn %>
          <%= link_to "削除する", blog_path(@blog.id),method: :delete, class: :prototype__btn %>
        </div>
         <% end %>
        <% end %>
    </div>
      <p class="prototype__hedding">
        <%= @blog.title %>
        <hr class="title_border">
      </p>
      <%= link_to @blog.user.name, "/users/#{@blog.user.id}", class: :prototype__user %>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title"></p>
          <p class="detail__message">
            <%= safe_join(@blog.matter.split("\n"),tag(:br)) %>
          </p>
        </div>
      </div>
      <div class="prototype__image">
        <%= image_tag @blog.image %>
      </div>
      <div class="prototype__comments">
        <% if user_signed_in? %>
           <%= form_with(model: [@blog, @comment], local: true) do |f|%>
            <div class="field">
               <%= f.label :text, "コメント" %><br />
               <%= f.text_area :text ,size: "50x5"%>
            </div>
            <div class="actions">
               <%= f.submit "送信する", class: :form__btn  %>
            </div>
           <% end %> 
        <% end %>
        <div class="comments_lists">
            <div class="comments_list">
            <% @comments.each do |comment| %>
                <div class="comment_users">
                  <%= link_to comment.user.name, "/users/#{comment.user_id}", class: :comment_user %>
                 <div class="comment_user_time">
                    <%= l comment.created_at %>
                  </div>
                  </div>
                  <p class="comment_texts"> <%= comment.text %></p>
               <% end %>
            </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>MYBLOGS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
             <div class="nav__right">
               <%= link_to  "#{current_user.name}さん", root_path, class: :greeting__link%>
               <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__btn %>
               </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
            <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
 
      <h2 class="page-heading">
        <%= @name %>
      </h2>     
         <div class="card__wrapper">
       <% @blogs.each do |blog| %>
       <div class="card">
         <%= link_to blog_path(blog.id) do %>
         <%= image_tag blog.image, class: "card__img" %>
      <div class="card__body">
         <%= link_to blog.title, blog_path(blog.id), class: :card__title%>
         <%= l blog.created_at %>
         <%= link_to blog.user.name, root_path,method: :get, class: :card__user %>
        </div>
       </div>
       <% end %>
      <% end %>
    
    </div>
  </div>
</div>